# -*- coding: utf-8 -*-
"""task01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjpjEKPVQNyPPFbODnL9Whhm76JXSss3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/API_SP.POP.TOTL_DS2_en_csv_v2_1402369.csv",skiprows=4)
df

df1=pd.read_csv("/content/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_1402369.csv")
df1

df.describe()

df1.describe()

df1.info()

df.head()

df.tail()

df1.head()

df1.tail()

df.columns

df2=df1.drop(['SpecialNotes', 'TableName', 'Unnamed: 5'], axis=1)
df2

df['Country Name'].unique()

df2['Country Code'].unique()

df2['Region'].unique()

df2.head()

df2.dropna(subset=['Region','IncomeGroup'])

# Bar Chart for Income Distributions by Regions
income_by_region = pd.crosstab(df2.IncomeGroup, df2.Region)
#plt.figure(figsize=(10, 6))
income_by_region.plot(kind='bar')
plt.xlabel("Income Group")
plt.ylabel("Number of Countries in Regions")
plt.title("Income Distribution by Regions")
plt.legend(title='Regions')
plt.show()

#top 10 countries based on population in the year 2021
df_sorted1 = df.sort_values(by='2021').head(10)
plt.figure(figsize=(10,6))
plt.barh(df_sorted1['Country Name'], df_sorted1['2021'])
plt.xlabel('Population')
plt.title('Top 10 Countries by Population in 2021')
#plt.gca().invert_yaxis()
plt.show()

#bottom 10 countied based on population in the year 1990
df_sorted2 = df.sort_values(by='1990').tail(10)
#plt.figure(figsize=(10, 6))
plt.barh(df_sorted2['Country Name'], df_sorted2['1990'], color='yellow')
plt.xlabel('Population')
plt.title('Bottom 10 Countries by Population in 1990')
#plt.gca().invert_yaxis()
plt.show()

# Histogram for population distribution in India from 1960-2022
data = df[df['Country Code'] == 'IND']
years = [str(year) for year in range(1960, 2023)]
population = data[years].values.flatten()
#plt.figure(figsize=(10, 6))
plt.hist(population,edgecolor='black')
plt.xlabel('Population')
plt.ylabel('Frequency')
plt.title('Population Distribution in India (1960-2022)')
plt.show()

# Histogram for population distribution in South Asia from 1960-2022
data = df[df['Country Code'] == 'AFG']
years = [str(year) for year in range(1960, 2023)]
population = data[years].values.flatten()
#plt.figure(figsize=(10, 6))
plt.hist(population,edgecolor='black')
plt.xlabel('Population')
plt.ylabel('Frequency')
plt.title('Population Distribution in South Asia from 1960-2022)')
plt.show()